concurrent = 1
check_interval = 0

[session_server]
  listen_address = "0.0.0.0:8093" #  listen on all available interfaces on port 8093
#  advertise_address = "runner-host-name.tld:8093"
  session_timeout = 1800

[[runners]]
  name = "95e8fe26ac7a"
  url = "http://gitlab:8888"
  token = "kwk-73fCXQNywiN38S2u"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "bitnami/ruby:2.3-ol-7"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    extra_hosts = ["gitlab:10.41.186.2"]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
